---
Name: comment-notifications-pages
Only:
  classexists: SiteTree
---
SiteTree:
  extensions:
    - CommentNotifiable
---
Name: comment-notifications
---
CommentingController:
  extensions:
    - CommentNotifier
